import { useState } from "react";
import { ArrowRight, Building2, Cake, Gift, HeartHandshake, PartyPopper, Sparkles } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";

const services = [
  { title: "Wedding gifting", icon: HeartHandshake, image: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=1000&q=85", summary: "Elegant favours for every celebration.", details: "Curated dry-fruit boxes, customised sleeves, name tags and delivery coordination for intimate celebrations or grand guest lists." },
  { title: "Corporate gifting", icon: Building2, image: "https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=1000&q=85", summary: "Thoughtful appreciation, beautifully branded.", details: "Welcome kits, festive hampers and client gifts with logo cards, tiered budgets and bulk dispatch planning." },
  { title: "Birthday & milestones", icon: Cake, image: "https://images.unsplash.com/photo-1464349153735-7db50ed83c84?w=1000&q=85", summary: "A small box with a big feeling.", details: "Personalised gift boxes for birthdays, anniversaries, housewarmings and every little reason to celebrate." },
  { title: "Festive hampers", icon: PartyPopper, image: "https://images.unsplash.com/photo-1513159446162-54eb8bdaa79b?w=1000&q=85", summary: "Seasonal gifting, made effortless.", details: "Diwali, Eid and holiday hampers assembled in small batches with a generous mix of premium favourites." },
  { title: "Build your own box", icon: Sparkles, image: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=1000&q=85", summary: "Your taste, your story, your box.", details: "Choose the varieties, size, note and finishing touches. We will help turn your brief into a memorable gift." },
  { title: "Bulk pantry orders", icon: Gift, image: "https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?w=1000&q=85", summary: "Better stocked homes and workplaces.", details: "Flexible recurring or one-off quantities for cafés, studios, offices and wellness spaces." },
];

export default function Services() {
  const [active, setActive] = useState(0);
  const navigate = useNavigate();
  const selected = services[active];
  return <main><section className="max-w-7xl mx-auto px-6 pt-16 pb-12 text-center"><p className="uppercase tracking-[.22em] text-xs text-clay font-medium mb-4">Gifting, considered</p><h1 className="font-display text-5xl md:text-6xl">Made for your memorable moments.</h1><p className="text-ink/65 max-w-2xl mx-auto mt-5 text-lg">Choose an occasion, then build a gift hamper with exactly the products you want.</p></section><section className="max-w-7xl mx-auto px-6 pb-16 grid lg:grid-cols-[1.25fr_.75fr] gap-7"><div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-5">{services.map((service, index) => { const Icon = service.icon; const isActive = active === index; return <button key={service.title} onClick={() => { setActive(index); navigate(`/gift-builder?service=${encodeURIComponent(service.title)}`); }} className={`group relative overflow-hidden rounded-xl2 min-h-64 text-left p-6 transition-all duration-300 focus-ring ${isActive ? "ring-2 ring-clay shadow-lg -translate-y-1" : "hover:-translate-y-1 hover:shadow-lg"}`}><img src={service.image} alt="" className="absolute inset-0 w-full h-full object-cover transition-transform duration-500 group-hover:scale-110"/><div className="absolute inset-0 bg-gradient-to-t from-ink/90 via-ink/30 to-transparent"/><div className="relative h-full flex flex-col justify-end text-cream"><Icon className="w-6 h-6 mb-auto"/><p className="font-display text-2xl">{service.title}</p><p className="text-sm text-cream/75 mt-1">{service.summary}</p></div></button>})}</div><aside className="lg:sticky lg:top-28 h-fit rounded-xl2 bg-ink text-cream p-8"><selected.icon className="w-8 h-8 text-clay mb-7"/><p className="text-clay uppercase tracking-[.18em] text-xs font-medium">Build your hamper</p><h2 className="font-display text-3xl mt-3">{selected.title}</h2><p className="text-cream/70 leading-relaxed mt-5">Select a card to choose premium products, set quantities and place the entire hamper in your cart.</p><ul className="mt-7 space-y-3 text-sm text-cream/85"><li>• Choose every product yourself</li><li>• Adjust quantities before checkout</li><li>• Place one simple order</li></ul><Link to={`/gift-builder?service=${encodeURIComponent(selected.title)}`} className="mt-8 inline-flex gap-2 items-center px-5 py-3 bg-cream text-ink rounded-full font-medium hover:bg-white">Build this hamper <ArrowRight className="w-4 h-4"/></Link></aside></section><section className="border-y border-line bg-white/40"><div className="max-w-7xl mx-auto px-6 py-12 grid sm:grid-cols-3 gap-8 text-center"><div><p className="font-display text-3xl">50+</p><p className="text-sm text-ink/60 mt-1">gifts can be tailored at once</p></div><div><p className="font-display text-3xl">3–7 days</p><p className="text-sm text-ink/60 mt-1">typical gifting lead time</p></div><div><p className="font-display text-3xl">One team</p><p className="text-sm text-ink/60 mt-1">from brief to doorstep</p></div></div></section></main>;
}
