import { useEffect, useState } from "react";
import { Pencil, Plus, Trash2, X } from "lucide-react";
import api from "../../api/client.js";
import AdminLayout from "../../components/AdminLayout.jsx";

const empty = { name: "", slug: "" };
export default function AdminCategories() {
  const [categories, setCategories] = useState([]); const [editing, setEditing] = useState(null); const [form, setForm] = useState(empty); const [error, setError] = useState("");
  const load = () => api.get("/products/categories").then(({ data }) => setCategories(data.categories));
  useEffect(() => { load(); }, []);
  const open = (category = null) => { setError(""); setEditing(category || {}); setForm(category ? { name: category.name, slug: category.slug } : empty); };
  async function save(event) { event.preventDefault(); setError(""); try { if (editing.id) await api.put(`/products/categories/${editing.id}`, form); else await api.post("/products/categories", form); setEditing(null); load(); } catch (e) { setError(e.response?.data?.error || "Could not save category"); } }
  async function remove(category) { if (!confirm(`Delete ${category.name}? Products will become uncategorised.`)) return; try { await api.delete(`/products/categories/${category.id}`); load(); } catch (e) { alert(e.response?.data?.error || "Could not delete category"); } }
  return <AdminLayout><div className="flex items-center justify-between mb-8"><div><h1 className="font-display text-3xl">Categories</h1><p className="text-sm text-ink/50 mt-1">Organise the storefront collection cards and shop filters.</p></div><button onClick={() => open()} className="flex gap-2 items-center px-4 py-2 rounded-full bg-ink text-cream text-sm"><Plus className="w-4 h-4"/> Add category</button></div><div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-4">{categories.map(category => <div key={category.id} className="border border-line bg-white/60 rounded-xl2 p-5 flex items-center justify-between"><div><p className="font-medium">{category.name}</p><p className="text-xs text-ink/45 mt-1">/shop?category={category.slug}</p></div><div className="flex gap-3"><button onClick={() => open(category)} aria-label="Edit category"><Pencil className="w-4 h-4"/></button><button onClick={() => remove(category)} aria-label="Delete category" className="text-red-500"><Trash2 className="w-4 h-4"/></button></div></div>)}</div>{editing !== null && <div className="fixed inset-0 bg-ink/40 z-50 grid place-items-center p-6"><form onSubmit={save} className="w-full max-w-md bg-cream rounded-xl2 p-6 space-y-4"><div className="flex justify-between"><h2 className="font-display text-xl">{editing.id ? "Edit category" : "New category"}</h2><button type="button" onClick={() => setEditing(null)}><X/></button></div><input required className="input" placeholder="Name" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })}/><input required pattern="[a-z0-9]+(-[a-z0-9]+)*" className="input" placeholder="Slug, e.g. dried-fruit" value={form.slug} onChange={e => setForm({ ...form, slug: e.target.value.toLowerCase().replace(/\s+/g, "-") })}/>{error && <p className="text-red-600 text-sm">{error}</p>}<button className="w-full py-3 rounded-full bg-ink text-cream">Save category</button></form></div>}</AdminLayout>;
}
