import { useEffect, useState } from "react";
import { Plus, Trash2, X } from "lucide-react";
import api from "../../api/client.js";
import AdminLayout from "../../components/AdminLayout.jsx";

const EMPTY = { code: "", description: "", discount_type: "percentage", discount_value: "", min_order_amount: "", max_discount_amount: "", usage_limit: "", expires_at: "" };

export default function AdminCoupons() {
  const [coupons, setCoupons] = useState([]);
  const [form, setForm] = useState(EMPTY);
  const [open, setOpen] = useState(false);
  const [error, setError] = useState("");
  const load = () => api.get("/coupons").then(({ data }) => setCoupons(data.coupons));
  useEffect(() => { load(); }, []);
  async function save(event) { event.preventDefault(); setError(""); try { await api.post("/coupons", form); setOpen(false); setForm(EMPTY); load(); } catch (err) { setError(err.response?.data?.error || "Could not create coupon"); } }
  async function remove(coupon) { if (!confirm(`Delete ${coupon.code}?`)) return; try { await api.delete(`/coupons/${coupon.id}`); load(); } catch (err) { alert(err.response?.data?.error || "Could not delete coupon"); } }
  const set = (field, value) => setForm((current) => ({ ...current, [field]: value }));
  return <AdminLayout><div className="flex items-center justify-between mb-8"><div><h1 className="font-display text-3xl">Coupons</h1><p className="text-sm text-ink/50 mt-1">Create and manage checkout discount codes.</p></div><button onClick={() => { setError(""); setOpen(true); }} className="flex gap-2 items-center px-4 py-2 rounded-full bg-ink text-cream text-sm"><Plus className="w-4 h-4" /> Add coupon</button></div>
    <div className="overflow-x-auto rounded-xl2 border border-line bg-white/60"><table className="w-full text-sm"><thead><tr className="text-left border-b border-line"><th className="p-4">Code</th><th className="p-4">Discount</th><th className="p-4">Usage</th><th className="p-4">Expires</th><th className="p-4" /></tr></thead><tbody>{coupons.map((coupon) => <tr key={coupon.id} className="border-b border-line last:border-0"><td className="p-4 font-semibold">{coupon.code}</td><td className="p-4">{coupon.discount_value}{coupon.discount_type === "percentage" ? "%" : "₹"}</td><td className="p-4">{coupon.used_count}{coupon.usage_limit !== null ? ` / ${coupon.usage_limit}` : ""}</td><td className="p-4">{coupon.expires_at ? new Date(coupon.expires_at).toLocaleDateString() : "Never"}</td><td className="p-4 text-right"><button onClick={() => remove(coupon)} className="text-red-500" aria-label={`Delete ${coupon.code}`}><Trash2 className="w-4 h-4" /></button></td></tr>)}</tbody></table>{!coupons.length && <p className="p-6 text-ink/40">No coupons yet.</p>}</div>
    {open && <div className="fixed inset-0 bg-ink/40 z-50 grid place-items-center p-6"><form onSubmit={save} className="w-full max-w-md bg-cream rounded-xl2 p-6 space-y-3"><div className="flex justify-between"><h2 className="font-display text-xl">New coupon</h2><button type="button" onClick={() => setOpen(false)}><X /></button></div><input required className="input" placeholder="Code, e.g. WELCOME10" value={form.code} onChange={(e) => set("code", e.target.value.toUpperCase())} /><input className="input" placeholder="Description" value={form.description} onChange={(e) => set("description", e.target.value)} /><div className="grid grid-cols-2 gap-3"><select className="input" value={form.discount_type} onChange={(e) => set("discount_type", e.target.value)}><option value="percentage">Percentage</option><option value="fixed">Fixed amount</option></select><input required type="number" min="0.01" step="0.01" className="input" placeholder="Value" value={form.discount_value} onChange={(e) => set("discount_value", e.target.value)} /></div><div className="grid grid-cols-2 gap-3"><input type="number" min="0" step="0.01" className="input" placeholder="Minimum order" value={form.min_order_amount} onChange={(e) => set("min_order_amount", e.target.value)} /><input type="number" min="0" step="0.01" className="input" placeholder="Max discount" value={form.max_discount_amount} onChange={(e) => set("max_discount_amount", e.target.value)} /></div><div className="grid grid-cols-2 gap-3"><input type="number" min="1" className="input" placeholder="Usage limit" value={form.usage_limit} onChange={(e) => set("usage_limit", e.target.value)} /><input type="datetime-local" className="input" value={form.expires_at} onChange={(e) => set("expires_at", e.target.value)} /></div>{error && <p className="text-red-600 text-sm">{error}</p>}<button className="w-full py-3 rounded-full bg-ink text-cream">Save coupon</button></form></div>}</AdminLayout>;
}
